import type MarkdownIt from 'markdown-it'
import footnote from 'markdown-it-footnote'

/**
 * Wrapper around 'markdown-it-footnote' plugin.
 *
 * Matches notes with corresponding rows in the article, and changes the html generated by the footnote plugin.
 */

export default function marginNotes(md: MarkdownIt): void {
  md.use(footnote)

  md.renderer.rules.footnote_block_open = () =>
    '<section class="margin-notes" aria-labelledby="margin-notes-label">\n' +
    '<h2 id="margin-notes-label" class="margin-notes__title">Notes</h2>\n'

  md.renderer.rules.footnote_block_close = () => '</section>\n'

  md.renderer.rules.footnote_open = (tokens, index, options, env, renderer) => {
    const meta = tokens[index].meta as { id: number }
    const anchorName = renderer.rules.footnote_anchor_name(tokens, index, options, env, renderer)
    const id = md.utils.escapeHtml(`fn${anchorName}`)
    const referenceId = md.utils.escapeHtml(`fnref${anchorName}`)
    const number = meta.id + 1

    return `<div class="margin-note-group" data-margin-note-ref="${referenceId}">\n` +
      `<MarginNote id="${id}" :number="${number}">`
  }

  md.renderer.rules.footnote_close = () => `</MarginNote>\n</div>\n`
}
